/** ORDER */
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const INCREAMENT = 'INCREAMENT';
export const DECREMENT = 'DECREMENT';

/** VISBLE SNACK BAR */
export const VISIBLE_SNACK_BAR = 'VISIBLE';
export const INVISIBLE_SNACK_BAR = 'INVISIBLE';

/** FETCH ALL CATEGORY */

export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_FAIL = 'GET_ALL_CATEGORY_FAIL';
